# YOLOv8 Configuration

model:
  name: "YOLOv8"
  architecture: "yolov8"
  
  # Model variants
  variant: "yolov8n"  # Options: yolov8n, yolov8s, yolov8m, yolov8l, yolov8x
  
  # Model parameters
  num_classes: 80
  depth_multiple: 0.33
  width_multiple: 0.25
  
  # Architecture details
  backbone:
    type: "CSPDarknet"
    activation: "SiLU"
    
  neck:
    type: "PAFPN"
    
  head:
    type: "Decoupled"
    anchors: "auto"

# Training configuration
training:
  batch_size: 16
  epochs: 300
  image_size: 640
  
  # Optimizer
  optimizer:
    type: "AdamW"
    lr: 0.01
    momentum: 0.937
    weight_decay: 0.0005
    
  # Learning rate schedule
  scheduler:
    type: "cosine"
    warmup_epochs: 3
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    
  # Augmentation
  augmentation:
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.0
    copy_paste: 0.0

# Inference configuration
inference:
  conf_threshold: 0.25
  iou_threshold: 0.45
  max_det: 300
  agnostic_nms: false
  
# Loss weights
loss:
  box: 7.5
  cls: 0.5
  dfl: 1.5
