version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
    command: python src/prediction_api.py
    
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: streamlit run web_app/app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - api

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    depends_on:
      - api
