# Main Configuration File
project:
  name: "Advanced Object Detection"
  version: "2.0.0"
  description: "Multi-model object detection system"
  author: "Computer Vision Team"

data:
  dataset_name: "custom_detection"
  classes:
    - "person"
    - "bicycle"
    - "car"
    - "motorcycle"
    - "airplane"
    - "bus"
    - "train"
    - "truck"
    - "boat"
    - "traffic_light"
    - "fire_hydrant"
    - "stop_sign"
    - "parking_meter"
    - "bench"
    - "bird"
    - "cat"
    - "dog"
    - "horse"
    - "sheep"
    - "cow"
  
  paths:
    raw_data: "data/raw"
    processed_data: "data/processed"
    annotations: "data/annotations"
    train_images: "data/processed/train/images"
    train_labels: "data/processed/train/labels"
    val_images: "data/processed/val/images"
    val_labels: "data/processed/val/labels"
    test_images: "data/processed/test/images"
    test_labels: "data/processed/test/labels"
  
  split_ratios:
    train: 0.7
    val: 0.2
    test: 0.1
  
  augmentation:
    enabled: true
    horizontal_flip: 0.5
    vertical_flip: 0.1
    rotation: 15
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
    noise: 0.05

models:
  available_models:
    - "yolov8n"
    - "yolov8s"
    - "yolov8m"
    - "yolov8l"
    - "yolov8x"
    - "faster_rcnn"
    - "ssd300"
    - "efficientdet_d0"
    - "efficientdet_d1"
  
  default_model: "yolov8s"
  
  yolo:
    input_size: 640
    conf_threshold: 0.25
    iou_threshold: 0.45
    max_detections: 300
  
  rcnn:
    input_size: 800
    conf_threshold: 0.5
    iou_threshold: 0.5
    max_detections: 100

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0005
  momentum: 0.937
  warmup_epochs: 3
  patience: 10
  save_period: 10
  device: "auto"  # auto, cpu, cuda, mps
  mixed_precision: true
  gradient_clipping: 10.0
  
  optimizer:
    type: "AdamW"  # SGD, Adam, AdamW
    params:
      lr: 0.001
      weight_decay: 0.0005
  
  scheduler:
    type: "CosineAnnealingLR"
    params:
      T_max: 100
      eta_min: 0.0001

evaluation:
  metrics:
    - "mAP"
    - "mAP50"
    - "mAP75"
    - "precision"
    - "recall"
    - "f1_score"
  
  iou_thresholds: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
  conf_threshold: 0.001
  max_detections: 300

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  max_file_size: 50  # MB
  allowed_extensions: [".jpg", ".jpeg", ".png", ".bmp", ".tiff"]

web_app:
  host: "0.0.0.0"
  port: 8501
  title: "Advanced Object Detection System"
  max_upload_size: 200  # MB

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/detection.log"
  
wandb:
  enabled: true
  project: "object-detection"
  entity: "your-team"
